#!/bin/bash

rm -rf x
mkdir x

(
	cd s
	cp --recursive --parents . ../x
)

(
	npx rollup x/script.js \
		-p @rollup/plugin-node-resolve \
		--format es \
		--file x/script.bundle.js
)

(
	cd x

	commit_id=$(git rev-parse --short HEAD)

	find . \
		-type f \
		-name "*.html" \
		-exec sed \
		-i "s/\$VERSION/${commit_id}/g" {} \;
)
